environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run coverage
  - npm tun test-chrome
  - npm run test-firefox
  - npm run test-ie
  - npm run codecov
build: off
